name: dev server

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"

      - name: Set up COMMON file
        run: echo "${{ secrets.COMMON }}" > ./src/main/resources/application-COMMON.properties
        shell: bash

      - name: Set up DEV file
        run: echo "${{ secrets.DEV }}" > ./src/main/resources/application-DEV.properties
        shell: bash

      - name: Set up Firebase Key file
        run: echo "${{ secrets.FIREBASE_KEY }}" > ./src/main/resources/static/firebase-adminsdk.json
        shell: bash

      - name: Set up GCS Key file
        run: echo "${{ secrets.GCS_KEY }}" > ./src/main/resources/static/gcp-img-role.json
        shell: bash

      - name: Set up Apple Key file
        run: echo "${{ secrets.APPLE_AUTH_KEY }}" > ./src/main/resources/static/AuthKey_ZJ4VQZNW7D.p8
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_PWD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_DEV_USERNAME }}/pochak-dev
          build-args: |
            SPRING_PROFILES_ACTIVE=DEV

      - name: Execute remote ssh & Deploy Dev server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo sh deploy.sh